// Copyright 2023 Princess B33f Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package helpers

const (
    ParameterValidation       = "parameter"
    ParameterValidationPath   = "path"
    ParameterValidationQuery  = "query"
    ParameterValidationHeader = "header"
    ParameterValidationCookie = "cookie"
    RequestBodyValidation     = "requestBody"
    Schema                    = "schema"
    ResponseBodyValidation    = "response"
    RequestBodyContentType    = "contentType"
    ResponseBodyResponseCode  = "statusCode"
    SpaceDelimited            = "spaceDelimited"
    PipeDelimited             = "pipeDelimited"
    DefaultDelimited          = "default"
    MatrixStyle               = "matrix"
    LabelStyle                = "label"
    Pipe                      = "|"
    Comma                     = ","
    Space                     = " "
    SemiColon                 = ";"
    Asterisk                  = "*"
    Period                    = "."
    Equals                    = "="
    Integer                   = "integer"
    Number                    = "number"
    Slash                     = "/"
    Object                    = "object"
    String                    = "string"
    Array                     = "array"
    Boolean                   = "boolean"
    DeepObject                = "deepObject"
    Header                    = "header"
    Cookie                    = "cookie"
    Path                      = "path"
    Form                      = "form"
    Query                     = "query"
    JSONContentType           = "application/json"
    JSONType                  = "json"
    ContentTypeHeader         = "Content-Type"
    Charset                   = "charset"
    Boundary                  = "boundary"
    FailSegment               = "**&&FAIL&&**"
)
