openapi: "3.1.0"
info:
  title: Discriminator Benchmark - oneOf (baseline)
  description: |
    Uses standard oneOf + discriminator pattern. The jsonschema library will
    brute-force validate against ALL schemas in the oneOf to find the match.
  version: "1.0.0"
servers:
  - url: /api/v3

paths:
  /ad_accounts/{ad_account_id}/bulk_actions:
    post:
      operationId: createBulkActions
      parameters:
        - name: ad_account_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  minItems: 1
                  maxItems: 50
                  items:
                    $ref: "#/components/schemas/BulkAction"
      responses:
        "201":
          description: Created

components:
  schemas:
    BulkAction:
      type: object
      required:
        - type
        - action
        - reference_id
        - entity_data
      properties:
        type:
          type: string
          enum: [CAMPAIGN, AD_GROUP, AD, POST, ASSET]
        action:
          type: string
          enum: [CREATE, EDIT]
        reference_id:
          type: string
          minLength: 1
          maxLength: 100
        entity_data:
          oneOf:
            - $ref: "#/components/schemas/CampaignInput"
            - $ref: "#/components/schemas/AdGroupInput"
            - $ref: "#/components/schemas/AdInput"
            - $ref: "#/components/schemas/PostInput"
            - $ref: "#/components/schemas/AssetInput"
          discriminator:
            propertyName: entity_type
            mapping:
              CAMPAIGN: "#/components/schemas/CampaignInput"
              AD_GROUP: "#/components/schemas/AdGroupInput"
              AD: "#/components/schemas/AdInput"
              POST: "#/components/schemas/PostInput"
              ASSET: "#/components/schemas/AssetInput"

    CampaignInput:
      type: object
      required:
        - entity_type
        - name
        - objective
        - daily_budget_micro
        - start_time
        - funding_instrument_id
      properties:
        entity_type:
          type: string
          const: CAMPAIGN
        name:
          type: string
          minLength: 1
          maxLength: 400
        objective:
          type: string
          enum: [AWARENESS, CONSIDERATION, CONVERSIONS, TRAFFIC, VIDEO_VIEWS, APP_INSTALLS]
        daily_budget_micro:
          type: integer
          minimum: 500000
        lifetime_budget_micro:
          type: integer
          minimum: 500000
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        funding_instrument_id:
          type: string
        configured_status:
          type: string
          enum: [ACTIVE, PAUSED]
          default: PAUSED

    AdGroupInput:
      type: object
      required:
        - entity_type
        - name
        - campaign_id
        - bid_strategy
        - goal_type
        - start_time
      properties:
        entity_type:
          type: string
          const: AD_GROUP
        name:
          type: string
          minLength: 1
          maxLength: 400
        campaign_id:
          type: string
        bid_strategy:
          type: string
          enum: [AUTO, MANUAL_CPC, MANUAL_CPM, MANUAL_CPV]
        bid_micro:
          type: integer
          minimum: 10000
        goal_type:
          type: string
          enum: [CLICKS, IMPRESSIONS, VIDEO_VIEWS, CONVERSIONS, APP_INSTALLS]
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        targeting:
          $ref: "#/components/schemas/Targeting"
        configured_status:
          type: string
          enum: [ACTIVE, PAUSED]
          default: PAUSED

    AdInput:
      type: object
      required:
        - entity_type
        - name
        - ad_group_id
        - post_id
      properties:
        entity_type:
          type: string
          const: AD
        name:
          type: string
          minLength: 1
          maxLength: 400
        ad_group_id:
          type: string
        post_id:
          type: string
        click_url:
          type: string
          format: uri
        configured_status:
          type: string
          enum: [ACTIVE, PAUSED]
          default: PAUSED

    PostInput:
      type: object
      required:
        - entity_type
        - headline
        - post_type
        - content
      properties:
        entity_type:
          type: string
          const: POST
        headline:
          type: string
          maxLength: 300
        body:
          type: string
          maxLength: 40000
        post_type:
          type: string
          enum: [IMAGE, VIDEO, TEXT, GALLERY, CAROUSEL, LINK]
        content:
          type: array
          minItems: 1
          items:
            oneOf:
              - $ref: "#/components/schemas/ImageContent"
              - $ref: "#/components/schemas/VideoContent"
              - $ref: "#/components/schemas/TextContent"
            discriminator:
              propertyName: content_type
              mapping:
                IMAGE: "#/components/schemas/ImageContent"
                VIDEO: "#/components/schemas/VideoContent"
                TEXT: "#/components/schemas/TextContent"
        destination_url:
          type: string
          format: uri

    AssetInput:
      type: object
      required:
        - entity_type
        - asset_type
        - url
      properties:
        entity_type:
          type: string
          const: ASSET
        asset_type:
          type: string
          enum: [IMAGE, VIDEO, LOGO]
        url:
          type: string
          format: uri
        width:
          type: integer
        height:
          type: integer

    ImageContent:
      type: object
      required:
        - content_type
        - url
      properties:
        content_type:
          type: string
          const: IMAGE
        url:
          type: string
          format: uri
        thumbnail_url:
          type: string
          format: uri
        destination_url:
          type: string
          format: uri
        width:
          type: integer
        height:
          type: integer
        call_to_action:
          type: string
          enum: [LEARN_MORE, SIGN_UP, SHOP_NOW, INSTALL, DOWNLOAD]

    VideoContent:
      type: object
      required:
        - content_type
        - url
      properties:
        content_type:
          type: string
          const: VIDEO
        url:
          type: string
          format: uri
        thumbnail_url:
          type: string
          format: uri
        destination_url:
          type: string
          format: uri
        duration_seconds:
          type: integer
          minimum: 1
          maximum: 180
        call_to_action:
          type: string
          enum: [LEARN_MORE, SIGN_UP, SHOP_NOW, INSTALL, DOWNLOAD, WATCH_MORE]

    TextContent:
      type: object
      required:
        - content_type
        - body
      properties:
        content_type:
          type: string
          const: TEXT
        body:
          type: string
          maxLength: 40000
        destination_url:
          type: string
          format: uri
        call_to_action:
          type: string
          enum: [LEARN_MORE, SIGN_UP, SHOP_NOW]

    Targeting:
      type: object
      properties:
        geos:
          type: object
          properties:
            included:
              type: array
              items:
                type: object
                properties:
                  country:
                    type: string
                  region:
                    type: string
        interests:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
        devices:
          type: array
          items:
            type: string
            enum: [DESKTOP, MOBILE, TABLET]
        age_range:
          type: object
          properties:
            min:
              type: integer
              minimum: 18
              maximum: 65
            max:
              type: integer
              minimum: 18
              maximum: 65
        gender:
          type: string
          enum: [ALL, MALE, FEMALE, OTHER]
