openapi: 3.0.2
info:
  title: Nullable Enum Test API
  version: 1.0.0
  description: Test specification for nullable enum validation
paths:
  /status:
    get:
      summary: Get status with nullable enum
      operationId: getStatus
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
    post:
      summary: Create status
      operationId: createStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /items:
    get:
      summary: Get items with nullable enum in array
      operationId: getItems
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    StatusResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
          description: Status field with nullable enum (no null in enum)
          enum:
            - active
            - inactive
            - pending
            - archived
          nullable: true
        priority:
          type: string
          description: Priority field with nullable enum (null already in enum)
          enum:
            - high
            - medium
            - low
            - null
          nullable: true
        category:
          type: string
          description: Non-nullable enum
          enum:
            - public
            - private
            - internal
    StatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - active
            - inactive
            - pending
            - archived
          nullable: true
        priority:
          type: string
          enum:
            - high
            - medium
            - low
            - null
          nullable: true
    Item:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
          description: Nested nullable enum
          enum:
            - available
            - sold
            - reserved
          nullable: true
        metadata:
          type: object
          properties:
            visibility:
              type: string
              description: Deeply nested nullable enum
              enum:
                - visible
                - hidden
              nullable: true
